
OPTIONS = -g -O0 -Wall

# Syntaxe : cible : dépendance1 dépendance2 ...
# Ensuite, la ou les ligne(s) débutant par une tabulation (\t) donne les commandes pour construire une cible
lab1: lab1.cpp
	g++ $(OPTIONS) -o lab1 lab1.cpp


clean :
	rm -f *.o
	rm -f lab1
	rm -f *~
